version: '3'

services:
  survey:
    image: parryk303/breath-of-fresh-airbnb:latest
    depends_on:
      - 'database'
    ports:
      - '3001:3001'

  database:
    image: mongo:latest
    ports:
      - "27017:27017"